// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/handlers/messageHandler.go

// Package mock_handlers is a generated GoMock package.
package mock_handlers

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	echo "github.com/labstack/echo/v4"
)

// MockMessageHandlerInterface is a mock of MessageHandlerInterface interface.
type MockMessageHandlerInterface struct {
	ctrl     *gomock.Controller
	recorder *MockMessageHandlerInterfaceMockRecorder
}

// MockMessageHandlerInterfaceMockRecorder is the mock recorder for MockMessageHandlerInterface.
type MockMessageHandlerInterfaceMockRecorder struct {
	mock *MockMessageHandlerInterface
}

// NewMockMessageHandlerInterface creates a new mock instance.
func NewMockMessageHandlerInterface(ctrl *gomock.Controller) *MockMessageHandlerInterface {
	mock := &MockMessageHandlerInterface{ctrl: ctrl}
	mock.recorder = &MockMessageHandlerInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMessageHandlerInterface) EXPECT() *MockMessageHandlerInterfaceMockRecorder {
	return m.recorder
}

// AllMessages mocks base method.
func (m *MockMessageHandlerInterface) AllMessages(ctx echo.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AllMessages", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// AllMessages indicates an expected call of AllMessages.
func (mr *MockMessageHandlerInterfaceMockRecorder) AllMessages(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AllMessages", reflect.TypeOf((*MockMessageHandlerInterface)(nil).AllMessages), ctx)
}

// CreateMessage mocks base method.
func (m *MockMessageHandlerInterface) CreateMessage(ctx echo.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateMessage", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateMessage indicates an expected call of CreateMessage.
func (mr *MockMessageHandlerInterfaceMockRecorder) CreateMessage(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateMessage", reflect.TypeOf((*MockMessageHandlerInterface)(nil).CreateMessage), ctx)
}
