// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/if1bonacci/lets-go-chat/internal/configs"
	"github.com/if1bonacci/lets-go-chat/internal/handlers"
	"github.com/if1bonacci/lets-go-chat/internal/repositories"
	"github.com/if1bonacci/lets-go-chat/internal/routing"
)

// Injectors from wire.go:

func InitializeDB() (configs.MongoDB, error) {
	env := configs.ProvideEnv()
	mongoDB := configs.ProvideMongoDB(env)
	return mongoDB, nil
}

func InitializeRouting() (routing.Routing, error) {
	env := configs.ProvideEnv()
	mongoDB := configs.ProvideMongoDB(env)
	messageRepository := repositories.ProvideMessageRepo(mongoDB)
	userRepository := repositories.ProvideUserRepo()
	authHandler := handlers.ProvideAuthHandler(messageRepository, userRepository)
	messageHandler := handlers.ProvideMessageHandler(messageRepository)
	chatRepository := repositories.ProvideChatRepo()
	chatHandler := handlers.ProvideChatHandler(messageRepository, userRepository, chatRepository)
	userHandler := handlers.ProvideUserHandler(userRepository)
	routingRouting := routing.ProvideRouting(authHandler, messageHandler, chatHandler, userHandler)
	return routingRouting, nil
}
