// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/configs/mongodb.go

// Package mock_configs is a generated GoMock package.
package mock_configs

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	mongo "go.mongodb.org/mongo-driver/mongo"
)

// MockMongoDBInterface is a mock of MongoDBInterface interface.
type MockMongoDBInterface struct {
	ctrl     *gomock.Controller
	recorder *MockMongoDBInterfaceMockRecorder
}

// MockMongoDBInterfaceMockRecorder is the mock recorder for MockMongoDBInterface.
type MockMongoDBInterfaceMockRecorder struct {
	mock *MockMongoDBInterface
}

// NewMockMongoDBInterface creates a new mock instance.
func NewMockMongoDBInterface(ctrl *gomock.Controller) *MockMongoDBInterface {
	mock := &MockMongoDBInterface{ctrl: ctrl}
	mock.recorder = &MockMongoDBInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMongoDBInterface) EXPECT() *MockMongoDBInterfaceMockRecorder {
	return m.recorder
}

// ConnectDB mocks base method.
func (m *MockMongoDBInterface) ConnectDB() *mongo.Client {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ConnectDB")
	ret0, _ := ret[0].(*mongo.Client)
	return ret0
}

// ConnectDB indicates an expected call of ConnectDB.
func (mr *MockMongoDBInterfaceMockRecorder) ConnectDB() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ConnectDB", reflect.TypeOf((*MockMongoDBInterface)(nil).ConnectDB))
}

// GetCollection mocks base method.
func (m *MockMongoDBInterface) GetCollection(collectionName string) *mongo.Collection {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCollection", collectionName)
	ret0, _ := ret[0].(*mongo.Collection)
	return ret0
}

// GetCollection indicates an expected call of GetCollection.
func (mr *MockMongoDBInterfaceMockRecorder) GetCollection(collectionName interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCollection", reflect.TypeOf((*MockMongoDBInterface)(nil).GetCollection), collectionName)
}
